# Generated by Django 5.0.3 on 2024-03-15 17:44

import django.db.models.deletion
import wagtail.images.models
import wagtailimagecaptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimagecaptions", "0005_auto_20231121_1134"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptionedExifImage",
            fields=[
                (
                    "captionedimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailimagecaptions.captionedimage",
                    ),
                ),
                ("exif_data", models.JSONField(blank=True, encoder=wagtailimagecaptions.models.DateTimeEncoder, null=True)),
                ("date_time_original", models.DateTimeField(blank=True, null=True)),
                ("camera_make", models.CharField(blank=True, max_length=255)),
                ("camera_model", models.CharField(blank=True, max_length=255)),
                ("lens_make", models.CharField(blank=True, max_length=255)),
                ("lens_model", models.CharField(blank=True, max_length=255)),
                ("focal_length", models.CharField(blank=True, max_length=255)),
                ("shutter_speed", models.CharField(blank=True, max_length=255)),
                ("aperture", models.CharField(blank=True, max_length=255)),
                ("iso_rating", models.CharField(blank=True, max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailimagecaptions.captionedimage",),
        ),
        migrations.CreateModel(
            name="CaptionedExifRendition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("filter_spec", models.CharField(db_index=True, max_length=255)),
                ("file", wagtail.images.models.WagtailImageField(height_field="height", width_field="width")),
                ("width", models.IntegerField(editable=False)),
                ("height", models.IntegerField(editable=False)),
                ("focal_point_key", models.CharField(blank=True, default="", editable=False, max_length=16)),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagtailimagecaptions.captionedexifimage")),
            ],
            options={
                "unique_together": {("image", "filter_spec", "focal_point_key")},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
